/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qianlee_A8CaptureJni */

#ifndef _Included_com_qianlee_A8CaptureJni
#define _Included_com_qianlee_A8CaptureJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qianlee_A8CaptureJni
 * Method:    IO_OpenDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_qianlee_A8CaptureJni_IO_1OpenDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qianlee_A8CaptureJni
 * Method:    IO_CloseDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qianlee_A8CaptureJni_IO_1CloseDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_qianlee_A8CaptureJni
 * Method:    IO_CaptureFileFullImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qianlee_A8CaptureJni_IO_1CaptureFileFullImage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_qianlee_A8CaptureJni
 * Method:    IO_CaptureBuf
 * Signature: ([B[I[I[I[B[I[I[I[B[I[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_qianlee_A8CaptureJni_IO_1CaptureBuf
  (JNIEnv *, jobject, jbyteArray, jintArray, jintArray, jintArray, jbyteArray, jintArray, jintArray, jintArray, jbyteArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     com_qianlee_A8CaptureJni
 * Method:    IO_SaveFile
 * Signature: (Ljava/lang/String;[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_qianlee_A8CaptureJni_IO_1SaveFile
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
